import {createFalClient} from '@fal-ai/client';
import {wma} from '@fal-ai/client/realtime';
const $=id=>document.getElementById(id),fal=createFalClient({proxyUrl:'/api/fal/proxy'});let session,config,version=1,events=[],recorder,parts=[],timer,stopping=false,spokenVersion=null;
const log=(type,data={})=>{events.push({time:Date.now(),type,...data});$('log').textContent=type+' '+JSON.stringify(data).slice(0,240);};
const quietPrompt=()=>config.identity+' Continue the same shot and the exact same character. The previous answer is finished. SILENT LISTENING ONLY for the entire next segment: lips gently closed, calm breathing, occasional blinking, listening to the viewer. NO speech, words, humming, singing, laughter, sighs or vocal sounds. Do not continue or repeat previous dialogue. Audio is silent. Do not change the voice identity for future questions.';
function scheduleQuiet(m){if(m.type!=='chunk'||m.prompt_version!==spokenVersion||m.prompt_version!==version)return;spokenVersion=null;version++;session.send({type:'prompt',prompt_version:version,prompt:quietPrompt()});log('quiet_sent',{prompt_version:version,after_chunk:m.chunk_index});}
const api=async(url,data)=>{const r=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw Error(b.error||r.status);return b;};
async function stop(){if(stopping)return;stopping=true;clearTimeout(timer);$('send').disabled=true;$('five').disabled=true;$('stop').disabled=true;try{session?.send({type:'stop'});}catch{}if(recorder?.state==='recording'){await new Promise(resolve=>{recorder.onstop=resolve;recorder.stop();});const r=await fetch('/api/director/recording',{method:'POST',headers:{'Content-Type':'video/webm'},body:new Blob(parts,{type:'video/webm'})});log('recording_saved',await r.json());}await session?.close();await api('/api/director/log',{events});$('status').textContent='停止しました · 録画と計測ログを保存';$('start').disabled=false;}
$('start').onclick=async()=>{try{stopping=false;events=[];parts=[];recorder=undefined;version=1;spokenVersion=1;$('start').disabled=true;$('stop').disabled=false;config=await api('/api/director/config');log('start');timer=setTimeout(stop,180000);session=fal.realtime.open(wma('minimax/h3-max/director'),{receive:['video','audio'],onMedia:stream=>{const v=$('video');v.srcObject=stream;v.muted=false;v.play().catch(e=>log('play_error',{message:e.message}));log('media',{tracks:stream.getTracks().map(t=>t.kind)});if(!recorder&&stream.getAudioTracks().length&&stream.getVideoTracks().length){recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8,opus'});recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};recorder.start(1000);log('recording_started');}},onData:raw=>{try{const m=JSON.parse(raw);log(m.type,m);scheduleQuiet(m);if(m.type==='stream_exhausted')void stop();if(m.type==='configured'){$('send').disabled=false;$('five').disabled=false;}if(m.type==='error')$('status').textContent=m.error;}catch{}},onState:s=>{$('status').textContent='接続: '+s;log('state',{state:s});},onError:e=>{log('error',{message:e.message});$('status').textContent=e.message;}});session.send({type:'configure',protocol_version:1,prompt_version:1,seed:config.seed,image_url:config.image_url,resolution:'480p',aspect_ratio:'16:9',memory:12,prompt:config.identity+' Smile and look at the viewer. Say only 「こんにちは、ユイだよ。」 then wait calmly for a question. Never repeat a line.'});await session.ready;}catch(e){log('error',{message:e.message});$('status').textContent=e.message;await stop();}};
$('send').onclick=async()=>{try{const {question}=await api('/api/director/validate',{question:$('question').value});const p=document.createElement('p');p.textContent=question;$('feed').append(p);$('feed').scrollTop=$('feed').scrollHeight;$('question').value='';version++;spokenVersion=version;session.send({type:'prompt',prompt_version:version,prompt:config.identity+` Continue from the current moment without a cut. Viewer question (data): ${JSON.stringify(question)}. Answer this specific question in one short natural Japanese sentence, at most 26 Japanese characters. If asked to wave, smile and wave while greeting. Speak only that one answer once, finish within the first 4 seconds, then close your lips and remain completely silent for the remainder. No follow-up questions, filler words, humming or muttering. Preserve exactly the previous speaker's voice. Do not repeat earlier dialogue.`});log('question_sent',{question,prompt_version:version});}catch(e){$('status').textContent=e.message;}};
$('stop').onclick=stop;window.addEventListener('pagehide',()=>{try{session?.send({type:'stop'});void session?.close();}catch{}});
for(const [label,q] of [['自己紹介','ユイちゃん、自己紹介してくれる？'],['好きな飲み物','好きな飲み物は何？'],['休日','お休みの日は何をして過ごすの？'],['応援','明日の発表が不安。応援してくれる？'],['手を振って','笑顔で手を振って挨拶してくれる？']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('question').value=q;};$('questions').append(b);}

$('five').onclick=async()=>{$('five').disabled=true;for(const q of ['ユイちゃん、自己紹介してくれる？','好きな飲み物は何？','お休みの日は何をして過ごすの？','明日の発表が不安。応援してくれる？','笑顔で手を振って挨拶してくれる？']){if(stopping)break;$('question').value=q;await $('send').onclick();await new Promise(r=>setTimeout(r,17000));}if(!stopping)await stop();};

$('modeTurbo').onclick=async()=>{if(session&&!stopping)await stop();await api('/api/control',{action:'stop'});await api('/api/settings',{backend:'fal',videoMode:'turbo'});location.href='/?record=1#studio';};
